{
 "title": "Inventory & Notification Consumers",
 "tags": [
  "kafka",
  "inventory-service",
  "notification-service"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka consumo - Inventory Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_consume_total{client_id=~\".*inventory.*\"}[1m])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Kafka consumo - Notification Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_consume_total{client_id=~\".*notification.*\"}[1m])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag - Inventory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_lag{client_id=~\".*inventory.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag - Notification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_lag{client_id=~\".*notification.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}